/**
 * PiKvmAutomator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export interface GoogleProtobufAny { 
  [key: string]: any | any;


    /**
     * The type of the serialized message.
     */
    type?: string;
}

